# Generated by Django 2.0 on 2018-10-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='loget_in',
            field=models.BooleanField(default=False),
        ),
    ]
