# Generated by Django 2.0 on 2018-10-07 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinit', models.CharField(max_length=10, unique=True, verbose_name='CI/NIT')),
                ('razon', models.CharField(max_length=100, verbose_name='Razon/Nombres')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('celular', models.IntegerField(blank=True, null=True, verbose_name='Celular')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['cinit'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad de Moviles')),
                ('direccion', models.TextField(verbose_name='Direccion de Origen')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['cliente', 'fecha'],
            },
        ),
    ]
