# Generated by Django 2.0 on 2018-10-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cinit',
            field=models.CharField(max_length=10, verbose_name='CI/NIT'),
        ),
    ]
