# Generated by Django 2.0 on 2018-10-08 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20181001_1804'),
        ('pedidos', '0002_auto_20181007_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.Conductor')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='aceptado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='rechazado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='terminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidovehiculo',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.Pedido'),
        ),
    ]
