# Generated by Django 2.0 on 2018-10-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='dlat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='dlong',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='olat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='olong',
            field=models.FloatField(null=True),
        ),
    ]
