# Generated by Django 2.0 on 2018-10-01 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, verbose_name='Placa')),
                ('marca', models.CharField(max_length=30, verbose_name='Marca Vehiculo')),
                ('tipo', models.CharField(max_length=30, verbose_name='Tipo Vehiculo')),
                ('color', models.CharField(max_length=10, verbose_name='Color Vehiculo')),
                ('imagen', models.ImageField(upload_to='vehiculo', verbose_name='Imagen de Vehiculo')),
                ('obs', models.TextField(verbose_name='Observaciones de Vehiculo')),
                ('conductor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='personal.Conductor')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'ordering': ['conductor', 'placa'],
            },
        ),
    ]
