# Generated by Django 2.0 on 2018-10-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='nro_chasis',
            field=models.CharField(default='', max_length=100, verbose_name='Numero de Chasis'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='soat',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='SI', max_length=100, verbose_name='SOAT'),
        ),
    ]
