# Generated by Django 2.0.3 on 2018-10-21 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal', '0002_auto_20181001_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(unique=True, verbose_name='Cedula de Identidad')),
                ('phone', models.IntegerField(verbose_name='Telefono de Referencia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
                'ordering': ['cedula'],
                'permissions': (('activate_operador', 'Activar Operador'), ('deactivate_operador', 'Desactivar Operador')),
            },
        ),
    ]
