# Generated by Django 2.0 on 2018-10-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_operador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conductor',
            options={'ordering': ['cedula'], 'permissions': (('activate_conductor', 'Activar Conductor'), ('deactivate_conductor', 'Desactivar Conductor')), 'verbose_name': 'Conductor', 'verbose_name_plural': 'Conductores'},
        ),
        migrations.AlterField(
            model_name='conductor',
            name='cedula',
            field=models.CharField(max_length=20, unique=True, verbose_name='Cedula de Identidad'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='nro_licencia',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=20, verbose_name='Numero de Licencia'),
        ),
    ]
