# Generated by Django 2.0.3 on 2018-10-14 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20181001_1804'),
        ('movile', '0002_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='origen',
            name='conductor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='personal.Conductor'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='conductor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='personal.Conductor'),
        ),
    ]
