# Generated by Django 2.0.3 on 2018-10-18 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20181001_1804'),
        ('pedidos', '0003_auto_20181007_2344'),
        ('movile', '0003_auto_20181014_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='personal.Conductor')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.Pedido')),
            ],
            options={
                'verbose_name': '_Ubicacion de Destino',
                'verbose_name_plural': '_Ubicaciones de Destino',
                'ordering': ['pedido', 'fecha', 'hora'],
            },
        ),
    ]
